/**
 *
 * $Id$
 */
package testModelWithXtextReference.validation;

import com.googlecode.efactory.xtextintegration.myDsl.Model;

/**
 * A sample validator interface for {@link testModelWithXtextReference.TestModelWithXtextReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestModelWithXtextReferenceValidator {
	boolean validate();

	boolean validateModel(Model value);
}
