/*
 * generated by Xtext
 */
package com.googlecode.efactory.xtextintegration;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends com.googlecode.efactory.xtextintegration.AbstractMyDslRuntimeModule {

}
